name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  macos:
    name: MacOS
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode:
          - 12.4
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Print Swift version
        run: swift --version
      - name: Run tests
        run: make test-swift

  linux:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make test-linux
